CREATE TABLE [dbo].[dim_date] (

	[Date] date NULL, 
	[Date_Key] int NULL, 
	[Year] int NULL, 
	[Month_Number] int NULL, 
	[Month_Name] varchar(max) NULL, 
	[Month_Short] varchar(max) NULL, 
	[Quarter_Number] int NULL, 
	[quarter] varchar(max) NULL, 
	[Year_Quarter] varchar(max) NULL, 
	[Month_Year] varchar(max) NULL, 
	[Year_Month] varchar(max) NULL, 
	[Week_Number] int NULL, 
	[Day] int NULL, 
	[Day_Name] varchar(max) NULL, 
	[Day_Short] varchar(max) NULL, 
	[Day_Of_Week] int NULL, 
	[Day_Of_Year] int NULL, 
	[Is_Weekend] int NULL, 
	[Is_Month_Start] int NULL, 
	[Is_Month_End] int NULL, 
	[Is_Quarter_Start] int NULL, 
	[Is_Quarter_End] int NULL, 
	[Is_Year_Start] int NULL, 
	[Is_Year_End] int NULL, 
	[Financial_Year] varchar(max) NULL, 
	[Financial_Quarter] varchar(max) NULL
);